# Generated by Django 4.2 on 2023-04-25 03:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_myuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='families',
        ),
        migrations.AddField(
            model_name='myuser',
            name='families',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
