# Generated by Django 4.2 on 2023-04-25 03:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_myuser_families_myuser_families'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='families',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
