# Generated by Django 4.2 on 2023-04-28 04:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_family_family_members_alter_myuser_families'),
    ]

    operations = [
        migrations.AddField(
            model_name='smcart',
            name='cart_orders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
