# Generated by Django 4.2 on 2023-04-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_smcart_cart_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='has_cart',
            field=models.BooleanField(default=False),
        ),
    ]
